server:
  port: 8084


spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/rabbitpro_db?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    username: root
    password: wenzio321q
    driver-class-name: com.mysql.cj.jdbc.Driver

